# Dependencies
markdown:         kramdown 
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Leia
tagline:          'BOOMSHAKALAKA'
description:      'Programmer, Dancer, Artist'
url:              leils.github.io
baseurl:          /

author:
  name:           'Leia Chang'
  url:            leiac.me

gems:             [jekyll-paginate, jekyll-gist]
paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

